[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/ANNIC/*"
  to = "http://102.216.253.12:7000/ANNIC/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
